### PR TITLE
Add juliacon talk script to docs

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by Vaibhavdixit02** [comment]
>Add the images to the PR comments itself and link them.

It looks to be working fine by placing it in `assets` folder as well https://gsa.sciml.ai/previews/PR42/tutorials/juliacon21/?

**Comment by Vaibhavdixit02** [comment]
Are you concerned about the repo size due to saving images there?

**Comment by ChrisRackauckas** [comment]
Yeah, images pile up really quickly, so I like to make sure each PR is clean to not have them.

**Comment by Vaibhavdixit02** [comment]
heatmapreg
morrisscat
sobolbars
sobolefastpred
sobolefastprey

**Comment by ChrisRackauckas** [comment]
(just make sure to squash merge).

**Pull request merged**
