### PR TITLE
Specialize on Gaussian and Independent copulas only. 

### PR DESCRIPTION
**Pull request by lrnv**

### CODE REVIEW

**Comment by lrnv** [comment]
@Vaibhavdixit02 Could you approve again ? had a typo

**Comment by lrnv** [comment]
@Vaibhavdixit02 again ? ;)

**Comment by lrnv** [comment]
This should be enough, test are passing. I am currently looking at what is in the docs, but the amount of dependencies is huge my laptop is precompiling stuff for the past 1/2 hour...

**Comment by Vaibhavdixit02** [comment]
That's okay, I can take care of that you have done a lot already haha! Thanks a ton!

**Pull request merged**
